services:
  activepieces:
    image: activepieces/activepieces:latest
    ports:
      - "8080:80"
    environment:
      - AP_REDIS_TYPE=MEMORY
      - AP_DB_TYPE=PGLITE
      - AP_FRONTEND_URL="http://localhost:8080"
    volumes:
      - ./ap_data:/root/.activepieces
    restart: always